// This file is auto-generated by the build system (make apply).
// It re-exports relevant fields from plugin.json.

import pluginManifest from '../../plugin.json';

const manifest = {
    id: pluginManifest.id,
    version: (pluginManifest as any).version || '',
};

export default manifest;
